twilio: # Twilio gateway configuration
  accountId: "ACdb8c8be629fe9e1e278ee9f79110ea66"
  accountToken:  "a16abdb3764f744b5ad12bab47a18d51"
  numbers: # Numbers allocated in Twilio
    - +443300582638
    - # Second number
    - # Third number
    - # ...
    - # Nth number
  messagingServicesId: "S800f449d0399ed014aae2bcc0cc2f2ec"  # demo Jude
  localDomain: "https://pillar-chat-service.herokuapp.com/" # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 1000 # Size of push pending queue

redphone:
  authKey: # Deprecated

turn: # TURN server configuration
  secret: # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: redis://h:p5c9d4d8c755201646fdcc9a5e1530a37a42a324a0422f6cc6d517aa69ffcf1e1@ec2-34-252-77-108.eu-west-1.compute.amazonaws.com:37489

directory: # Redis server configuration for directory cluster
  url: redis://h:p5c9d4d8c755201646fdcc9a5e1530a37a42a324a0422f6cc6d517aa69ffcf1e1@ec2-34-252-77-108.eu-west-1.compute.amazonaws.com:37489

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: opqivwsgqdpsaz
  password: f54ae206f25e6788dce5a392e6051e8eeafa749441337ecce4e87ce9c35d510f
  url: postgres://opqivwsgqdpsaz:f54ae206f25e6788dce5a392e6051e8eeafa749441337ecce4e87ce9c35d510f@ec2-54-217-245-53.eu-west-1.compute.amazonaws.com:5432/devje5jnora2k2

attachments: # AWS S3 configuration
  accessKey:
  accessSecret:
  bucket:

profiles: # AWS S3 configuration
  accessKey: none
  accessSecret: none
  bucket: none
  region: none

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "clhgtugujbupjk"
  password: "f38bf584898b10ba3199ef59aa4be87795f2d855221289f6da414da80b4def61"
  url: postgres://clhgtugujbupjk:f38bf584898b10ba3199ef59aa4be87795f2d855221289f6da414da80b4def61@ec2-54-217-245-66.eu-west-1.compute.amazonaws.com:5432/d9rb2n7ao8an8e

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:

gcm: # GCM Configuration
  senderId: 811306482558
  apiKey: AAAAvOWie34:APA91bEsQ2G7iHyAjZFmXTvzN6ox_HKz2w6XmPKmUGY4FErvTjbz16KCsEnyV7bGaOYN4yLRVkof8oL9fFv5BAFi3kTsOOgQnuI7KtWpW7Rsl66f8gTEW6NH2Bp1lA-K6DYKBi7HGO48 

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: config/example.keystore
      keyStorePassword: example
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: config/example.keystore
      keyStorePassword: example
      validateCerts: false